import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SidebarProvider } from "./components/common/sidebar";
import { SidebarToggle } from "./components/chat/header/sidebar-toggle";
import { SidebarPage } from "./components/chat/sidebar";
import { useSidebar } from "./components/common/sidebar";
import { SharedDataProvider } from "./context/sharedDataContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >

        <SidebarProvider>
          <SharedDataProvider>
            <div className="flex transition-all duration-300">
              <SidebarPage /> {/* will slide in/out */}
              <div className="flex-1 transition-all duration-300">
                {children}
              </div>
            </div>
          </SharedDataProvider>
        </SidebarProvider>

      </body>
    </html>
  );
}
